---
microk8s_channel: "1.31/stable"

microk8s_addons:
  - dns
  - hostpath-storage

microk8s_metallb_enabled: true
microk8s_metallb_range: "10.10.10.200-10.10.10.220"

cluster_user: foobar

wait_for_ssh_timeout: 600
